# Generated by Django 3.0.2 on 2020-01-15 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('journal', models.IntegerField()),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('number1', models.CharField(max_length=12)),
                ('number2', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('comment', models.CharField(max_length=500)),
                ('cdate', models.DateField(auto_now_add=True)),
                ('udate', models.DateField(auto_now=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuser', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification', to='utils.Enum')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='utils.Enum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('uuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
